name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    types: [synchronize, reopened, labeled]
    branches:
      - master

jobs:
  lint:
    name: cpplint
    if: ${{ github.event_name == 'push' || contains(join(toJson(github.event.pull_request.labels.*.name)), 'ready-for-testing') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Cpplint
        run: |
          cd .linters/cpp && ln -snf hooks/pre-commit.sh
          ./pre-commit.sh $(git --no-pager diff --name-only $(git log --oneline -n 1 | cut -d ' ' -f 1,5) | sed -E 's/(.*)/..\/..\/\1/g')

  gcc_build:
    name: GCC Build
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos7
          - ubuntu1804
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Prepare
        run: |
          mkdir -p ~/.ssh
          cp ./ci/deploy_key ~/.ssh/id_rsa
          chmod 0400 ~/.ssh/id_rsa
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - name: CMake
        run: |
          cmake -E make_directory build
          cmake \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_TESTING=on \
            -B build/
      - name: Make
        run: cmake --build build/ -j $(nproc)
      - name: CTest
        timeout-minutes: 30
        working-directory: build
        run: ctest -j $(nproc) --timeout 400 --output-on-failure

  clang_build:
    name: Clang Build
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos7
          - ubuntu1804
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
      env:
        ASAN_SYMBOLIZER_PATH: /opt/vesoft/toolset/clang/9.0.0/bin/llvm-symbolizer
        ASAN_OPTIONS: fast_unwind_on_malloc=0
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Prepare
        run: |
          mkdir -p ~/.ssh
          cp ./ci/deploy_key ~/.ssh/id_rsa
          chmod 0400 ~/.ssh/id_rsa
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - name: CMake
        run: |
          cmake -E make_directory build
          cmake \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_BUILD_TYPE=Debug \
            -DENABLE_ASAN=on \
            -DENABLE_UBSAN=on \
            -DENABLE_TESTING=on \
            -B build/
      - name: Make
        run: cmake --build build/ -j $(nproc)
      - name: CTest
        timeout-minutes: 30
        working-directory: build
        run: ctest -j $(nproc) --timeout 400 --output-on-failure
